### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by trix1210** [taiwo-adewale/doppell#1]
several files are missing - please upload them and include the .sql file. thanks!

**Comment by taiwo-adewale** [comment]
I have uploaded the missing files. You can check out the readme on how to setup the project.

**Comment by trix1210** [comment]
> I have uploaded the missing files. You can check out the readme on how to setup the project.

Thanks very much! Its a really-nice clean layout. Well done!

**Comment by taiwo-adewale** [comment]
Thanks
